app:
  multibanco-key: CHD-841325
  mbway-key: QYZ-455570
  anti-fishing-key: 18d056b18dd94416a6297d9abe42c09e
quarkus:
  oidc:
    auth-server-url: https://keycloak.bookanapp.org/realms/BAA
  rest-client:
    multibanco-client:
      uri: https://ifthenpay.com/api/multibanco/reference/init
    mbway-client:
      uri: https://mbway.ifthenpay.com/ifthenpaymbw.asmx
    keycloak-client:
      uri: https://keycloak.bookanapp.org/realms/BAA/protocol/openid-connect/token
  resteasy-reactive:
    path: /api/v1
  datasource:
    db-kind: mysql
    username: baa
    password: Dafundo1/
    jdbc:
      url: jdbc:mysql://localhost:3306/appointment?autoReconnect=true&useUnicode=true
  http:
    port: 8091

"%dev":
  app:
    multibanco-key: CHD-841325
    mbway-key: QYZ-455570
  quarkus:
    http:
      cors: true
    log:
      category:
        "org.apache.http":
          level: ALL
        "io.quarkus.oidc":
          level: DEBUG
    datasource:
      db-kind: mysql
      username: baa
      password: Dafundo1/
      jdbc:
        url: jdbc:mysql://localhost:3306/appointment?autoReconnect=true&useUnicode=yes&characterEncoding=UTF-8
    rest-client:
     multibanco-client:
       uri: https://ifthenpay.com/api/multibanco/reference/sandbox
     itp-credit-card-client:
       uri: https://ifthenpay.com/api/creditcard/init/AAA-000000
     keycloak-client:
       uri: https://keycloak.bookanapp.org/realms/BAA/protocol/openid-connect/token
    oidc:
      auth-server-url: https://keycloak.bookanapp.org/realms/BAA
      tls:
        verification: none
"%test":
  app:
    multibanco-key: CHD-841325
    mbway-key: QYZ-455570
  quarkus:
    oidc:
      auth-server-url: https://keycloak.bookanapp.org/realms/BAA
      tls:
        verification: none
    log:
      category:
        "io.quarkus.oidc":
          level: DEBUG
        "org.apache.http":
          level: DEBUG
        "org.jboss.resteasy.reactive.client.logging":
          level: DEBUG
    rest-client:
      logging:
        scope: request-response
      multibanco-client:
        uri: https://ifthenpay.com/api/multibanco/reference/sandbox
      itp-credit-card-client:
        uri: https://ifthenpay.com/api/creditcard/init/AAA-000000
      keycloak-client:
        uri: https://keycloak.bookanapp.org/realms/BAA/protocol/openid-connect/token
    datasource:
      db-kind: h2
      username: sa
      password: sa
      jdbc:
        url: jdbc:h2:mem:appointment;DATABASE_TO_UPPER=false;DB_CLOSE_DELAY=-1
    hibernate-orm:
      database:
        generation: drop-and-create
